### ISSUE TITLE
Error: Was unable to obtain:  from context.

### ISSUE THREAD

**Issue by centrodph** [dkershner6/jest-coverage-commenter-action#161]
I'm getting an error from this line:

https://github.com/dkershner6/jest-coverage-commenter-action/blob/master/src/tasks/postComment.ts#L21

<img width="599" alt="Screen Shot 2021-10-26 at 13 29 27" src="https://user-images.githubusercontent.com/2073951/138921573-6377ec05-47bb-45ac-86e4-63aac3ccb672.png">

and I'm using this config:

```
      - name: Coverage
        uses: dkershner6/jest-coverage-commenter-action@v1
        with:
          github_token: "${{ secrets.TOKEN }}"
          test_command: "npm run test"
```

Any help is welcome
