### ISSUE TITLE
Existing comment is not updated for organization bot

### ISSUE THREAD

**Issue by neveenatik** [dkershner6/jest-coverage-commenter-action#167]
We recently started using jest-coverage-commenter-action which serves our need very well accept for updating coverage comment every time the job is triggered.
Unfortunately it is always creating a new comment
Here is the part of the workflow which runs the test coverage job:
```yaml
test-coverage:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
                  node-version: '16.14.0'
                  registry-url: https://npm.daznplatform.com/
                  scope: '@dazn'

            - name: Install Root NPM packages
              run: |
                  npm config set //npm.daznplatform.com/:_authToken ${{ secrets.GLOBAL_JFROG_ARTIFACTORY_TOKEN }}
                  npm ci

            - name: Comment with Test Coverage
              uses: dkershner6/jest-coverage-commenter-action@v1
              with:
                  github_token: '${{ secrets.GLOBAL_GITHUB_TOKEN }}'
                  test_command: 'npm run test -- --coverage'
                  reporter: 'text-summary'
```

looking at [this part](https://github.com/dkershner6/jest-coverage-commenter-action/blob/master/src/tasks/postComment.ts#L59) of the code this is not supposed to happen 
```javascript
 if (existingComment?.id) {
    info(`Previous comment found: ${existingComment.id}`);
    await github.issues.updateComment({
        issue_number: prNumber,
        comment_id: existingComment.id,
        repo,
        owner,
        body: commentBody,
    });
}
```
My guess is as these jobs are ran by organization bot it might be that the value of `user.type` is not [`Bot`](https://github.com/dkershner6/jest-coverage-commenter-action/blob/master/src/tasks/postComment.ts#L38) which might be the reason the existing comment is not found in the first place.
Can I suggest to add an optional input for example `comment_author` maybe to solve that issue?
I'm happy to open a PR if you agree on the cause and the approach
